### ISSUE TITLE
Separate nodeSelector for controller and node components

### ISSUE THREAD

**Issue by sergeyberezansky** [DrFaust92/terraform-kubernetes-ebs-csi-driver#40]
Currently, extra_node_selectors are used for both node and controller components.
However, this should be separated.

Example:
EKS cluster with autoscaler, with 1 on-demand node, and all others are spot appliances.
CSI node components should run on all nodes, while controller should only run on on_demand node
Cannot be set.

**Comment by sergeyberezansky** [comment]
#41

**Comment by DrFaust92** [comment]
Closed by #41. Thanks @sergeyberezansky!
