### ISSUE TITLE
Bump CSI driver to v1.0.0

### ISSUE THREAD

**Issue by DrFaust92** [DrFaust92/terraform-kubernetes-ebs-csi-driver#49]

**Comment by hdiass** [comment]
Why is this locked to version 0.8.1 ? This image doens't support prometheus metrics export

**Comment by hdiass** [comment]
Is there way we can speed this update up?

**Comment by hdiass** [comment]
The way the code is implemented it won't allow version change, only image itself

**Comment by DrFaust92** [comment]
Should be ok in new version plus new default. please open a new issue if the problem persists
