### ISSUE TITLE
Wrong Terraform Version

### ISSUE THREAD

**Issue by flametuner** [DrFaust92/terraform-kubernetes-ebs-csi-driver#51]
The **required_providers** is probably wrong and it's using the following version constraint:

```
terraform {  
    required_version = "&gt;= 0.12.6"
    required_providers {    
        kubernetes = ">= 1.11.4" 
        terraform  = "~> 3.40.0"  
    }
}
```

It probably should be `aws` instead of `terraform`.

It's causing errors while using `terraform init`

**Comment by nirmalpathak** [comment]
The `terraform init` fails with the following error.

`│ Error: Invalid dependency on built-in provider
│ 
│ Cannot use terraform.io/builtin/terraform: built-in providers do not support explicit version constraints.`

**Comment by DrFaust92** [comment]
Fixed https://github.com/DrFaust92/terraform-kubernetes-ebs-csi-driver/releases/tag/v2.9.1
