### ISSUE TITLE
Doens't work on k8s 1.22

### ISSUE THREAD

**Issue by hdiass** [DrFaust92/terraform-kubernetes-ebs-csi-driver#77]
Hello,

resource "kubernetes_csi_driver" "ebs" {

needs to be changed to kubernetes_csi_driver_v1 resource.. tho we need to keep retrocompability. 

Thanks

**Comment by shadowrider-pl** [comment]
On https://registry.terraform.io/modules/DrFaust92/ebs-csi-driver/kubernetes/latest there is still Version 2.18.3 (latest)

**Comment by mr-kelly** [comment]
I think I found the same problem?

https://github.com/DrFaust92/terraform-kubernetes-ebs-csi-driver/issues/79

**Comment by mr-kelly** [comment]
> Hello,
> 
> resource "kubernetes_csi_driver" "ebs" {
> 
> needs to be changed to kubernetes_csi_driver_v1 resource.. tho we need to keep retrocompability.
> 
> Thanks

Thanks. I fixed my problem by manually change to `kubernetes_csi_driver_v1`

**Comment by DrFaust92** [comment]
Fixed via #80 please use latest version
