### ISSUE TITLE
All steps work..except... "ebs_csi_driver_controller.kubernetes_csi_driver...  the server could not find the requested resource"

### ISSUE THREAD

**Issue by mr-kelly** [DrFaust92/terraform-kubernetes-ebs-csi-driver#79]
│ Error: the server could not find the requested resource
│ 
│   with module.ebs_csi_driver_controller.kubernetes_csi_driver.ebs,

<img width="858" alt="image" src="https://user-images.githubusercontent.com/520852/171367397-0d2d6ab9-c174-4722-b988-8a9cd8581bde.png">

I stuck in this step..what should I do next?

**Comment by mr-kelly** [comment]
I fixed this problem by modify the `kubernetes_csi_driver` to `kubernetes_csi_driver_v1` in the local terraform .tf files

**Comment by DrFaust92** [comment]
Fixed via #80 please use latest version
